# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
