# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170206_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='note_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
