# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170211_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
