# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20170216_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
