# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170216_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='static/male.png', upload_to='profile_images'),
        ),
    ]
