# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20170218_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(max_length=128),
        ),
    ]
