# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20170218_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
