# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20170218_1422'),
        ('blog', '0028_auto_20170217_2054'),
    ]

    operations = [
    ]
