# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_userprofile_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pages',
            field=models.ManyToManyField(default=0, related_name='pages', to='blog.Page'),
        ),
    ]
