# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20170325_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pages',
            field=models.ManyToManyField(default='', related_name='pages', to='blog.Page'),
        ),
    ]
