# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20170325_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pages',
            field=models.ManyToManyField(default=0, related_name='pages', to='blog.Page'),
        ),
    ]
