# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20170326_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(default=0, related_name='author', to='blog.UserProfile')),
                ('subscriber', models.ManyToManyField(default=0, related_name='subscriber', to='blog.UserProfile')),
            ],
        ),
    ]
