# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribers',
        ),
    ]
