# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20170326_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(default=0, related_name='author', to='blog.UserProfile')),
                ('subscriber', models.ManyToManyField(default=0, related_name='subscriber', to='blog.UserProfile')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
