# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0043_auto_20170326_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='author',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='author',
            field=models.ManyToManyField(default=0, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscriber',
            field=models.ManyToManyField(default=0, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
