# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20170326_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
